default['java']['install_flavor'] = "openjdk"
default['java']['version']['major'] = "7"
default['java']['version']['minor'] = "55"
default['java']['root'] = "/usr/java"
default['java']['home'] = "#{node['java']['root']}/default"
default['java']['oracle']['url'] = "http://localhost/"
default['java']['oracle']['rpm'] = "jdk-7u55-linux-x64.rpm"
